name: Build Plugins Release

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'corretto'
        cache: maven


    - uses: actions/checkout@v4
      with:
        repository: nsherry4/Peakaboo
        ref: ${{ github.ref }}
        path: ./Peakaboo

    - name: Install base Peakaboo to Maven's local package store
      run: mvn -B install --file pom.xml
      working-directory: ./Peakaboo


    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with: 
        name: Plugins
        path: Plugins
        
